apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"               # Set to true for using managed identity.
    userAssignedIdentityID: SOME-GUID          # This is the objectID of the SPN used to authenticate. Get it via "az aks show -n xxxaks -g myResourceGroup --query "addonProfiles.azureKeyvaultSecretsProvider.identity.clientId" --output tsv".
    keyvaultName: aks-train-dev-kv             # Set to the name of your key vault.
    tenantId: SOME-GUID                        # The tenant ID where the application is registered.
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret                        # object types: secret, key, or cert.
          objectVersion: ""                         # [OPTIONAL] object versions, default to latest if empty.
  secretObjects:
    - secretName: myappsecrets                      # This creates a new k8s secrectobject called "myappsecrets". 
      type: Opaque
      data:
      - objectName: ExampleSecret                   # This finds a secret in the key vault called "ExampleSecret"   
        key: secretKey                              # This maps the value of secret into a new key called "secretkey".
